### ISSUE TITLE
[2.1-27] Load user Logins and villiages

### ISSUE THREAD

**Issue by kepaik** [SanaMobile/vaccine_registry#18]
We still need to discuss how the user logins, and villages are loaded into the server.

**Comment by AnnaSchrimpf** [comment]
Could you clarify what you mean by "manual batch processing" here? If it is either manual selection of villages from server interface or us sending lists to be pushed by SANA neither seems feasible. We are planning on generating logins based on ANM info, training them in batches of 30 at a time, so we have 24 hrs to generate logins before handing them to ANMs.

**Comment by EnikiE** [comment]
I think this can be closed? we seem to be in a stable state here, and have tested uploading anms @AnnaSchrimpf @ewinkler
