### ISSUE TITLE
VACC-ID state and validation issue.

### ISSUE THREAD

**Issue by kepaik** [SanaMobile/vaccine_registry#26]
if looking to ID child, when not in system, automatically assumes it's a new child.

**Comment by ewinkler** [comment]
Designed to regard as new child when ID scanned or manually entered and not found.

**Comment by kepaik** [comment]
This seems tricky, because what if they mis-enter the barcode? (which was what I had done...)

**Comment by ewinkler** [comment]
Ideally, I would say have them hit a back button but we didn't allow for this. The logic makes it difficult to have the back flow in a well behaved manner. We could probably come up with a workaround but it would take some time.

**Comment by ewinkler** [comment]
Does check for an existing record but advances to new patient registration scree r08 instead of r09.
