### ISSUE TITLE
Crash after back out of "Scan"

### ISSUE THREAD

**Issue by kepaik** [SanaMobile/vaccine_registry#33]
then back out, then manual entry.  4x, then crash.

**Comment by kepaik** [comment]
Only way to avoid it is by clicking "Cancel", which appropriately backs out.

**Comment by kepaik** [comment]
Oddly, does NOT happen on the confirm parent AADHAR screen. Weird.

**Comment by kepaik** [comment]
Not fixed at the moment. Hotfix: Back out to main entry screen to reset protocol, to avoid crash.

**Comment by ewinkler** [comment]
Rolled back hotfix. Normal behavior should be returned.

**Comment by AnnaSchrimpf** [comment]
No longer an issue.
