### ISSUE TITLE
"(0601) Key Messages" are too long and not user friendly

### ISSUE THREAD

**Issue by kepaik** [SanaMobile/vaccine_registry#36]
Text on screen is not usable.
Recommend condensing to concise crucial points.

**Comment by AnnaSchrimpf** [comment]
We have discussed with with the team and finalized the messages: while everyone agreed that even shorter/fewer messages than the ones below would be desirable, we also have to be in line with what was agreed with the government. 

These are the final versions:

1. Vaccine administered today and the diseases it prevents
आज लगाया गया टीका और वह किस-किस बीमारी से बचाएगा|

2. Date and time of next due vaccine
अगले टीकाकरण के लिए कब और कहाँ आना है|

3. Side-effects of vaccine and its remedy
आज लगे टीके के सामान्य दुष्प्रभाव एवं उनका निदान|

4. Keep MCP card carefully and bring it on the next visit
टीकाकरण कार्ड सुरक्षित रखें और अगली बार अवश्य साथ लायें |

5. Reminder to bring child and guardian’s  AADHAAR card
अगली बार बच्चे एवं अभिभावक का आधार कार्ड साथ लाना न भूलें|
