### ISSUE TITLE
[2.1-28] Unable to move beyond scanning of child aadhar 

### ISSUE THREAD

**Issue by AnnaSchrimpf** [SanaMobile/vaccine_registry#40]
Unable to move beyond screen (0101) Scan Child AAADHAR through any route.
1) Press "Scan Child AADHAR" -> successful scan -> returns to same screen rather than moving forward
2) Press "Manually Enter AADHAR" -> Nothing happens 
3) Press "No Child AADHAR present" ->  Nothing happens 
In some cases route 2) and 3) lead to a "Back" button appearing in top left of screen. Pressing back button has no effect, except for button to disappear.  

Going back and forth between these routes: In some cases triggers "Unfortunately, SANA has stopped responding" -> forced to quit client

**Comment by kepaik** [comment]
This is very unfortunate and related to known issue #33. It is a top priority.

**Comment by AnnaSchrimpf** [comment]
Yes, that works if no prior scan was attempted. If it makes sense from your perspective, I can continue testing based on this route, or hold off until next release.

**Comment by kepaik** [comment]
If it is not too much trouble, please continue testing with only manual entry. It is only the scan bug that persists.

**Comment by AnnaSchrimpf** [comment]
This is resolved, as far as we can tell.
