### ISSUE TITLE
[2.1-28] Client speed and "Loading Procedure" pop-up

### ISSUE THREAD

**Issue by AnnaSchrimpf** [SanaMobile/vaccine_registry#41]
The client is significantly slower than previous versions. Display of "Loading Procedure" pop-up between screens interrupts user flow and should be removed.

**Comment by kepaik** [comment]
Is this at all times or perhaps following #40?

**Comment by AnnaSchrimpf** [comment]
All the time - also after village selection in home screen and pressing "Record a child visit"

**Comment by kepaik** [comment]
There is a chance it's related to the scan bug. Could you try uninstalling and reinstalling and seeing if it persists?

**Comment by AnnaSchrimpf** [comment]
Issue persists - I have already wiped and re-installed 5+ times to check the consistency of the scanning bug.

**Comment by kepaik** [comment]
Ok understood. Will look into it. To confirm, you run into the performance issues without attempting a scan?

**Comment by AnnaSchrimpf** [comment]
Confirmed. Issue occurs before scan attempted.

**Comment by ewinkler** [comment]
Pop up removed. Pause/resume cycle updated which should reduce the system load and improve the performance issues. Will continue to monitor.

**Comment by AnnaSchrimpf** [comment]
This seems resolved.
