### ISSUE TITLE
[2.1-28.2] Status display of form uploading progress

### ISSUE THREAD

**Issue by AnnaSchrimpf** [SanaMobile/vaccine_registry#49]
As discussed, the team's preferred solution would be to add a display to the home screen like the one displayed below, where one of the three options would display below "Status."
But we're open to alternatives that convey the same info but are easier to implement.

![screen shot 2016-10-04 at 7 35 52 pm](https://cloud.githubusercontent.com/assets/5496869/19097508/54bb2ddc-8a73-11e6-86ae-aa25632f80b2.png)

**Comment by kepaik** [comment]
@ewinkler You should add a text label to the color code.
