### ISSUE TITLE
[2.1-27] Not allowed to move forward after "confirm child"

### ISSUE THREAD

**Issue by kepaik** [SanaMobile/vaccine_registry#5]
App (sometimes) does not allow to move forward after “confirm child” when lookup was successful:
After entering several records, I was again no longer able to move beyond “confirm child” after successfully looking up based on either Aadhar or barcode lookup. These cases again triggered "Unfortunately, Sana has stopped responding.” The only way to fix this was to wipe the app and reinstall. This issue preceded issue A but followed issue C, though not immediately.

**Comment by kepaik** [comment]
Have yet to replicate...

**Comment by ewinkler** [comment]
Fixed
