### ISSUE TITLE
 [2.1-28.2] Pushing of automatic app updates

### ISSUE THREAD

**Issue by AnnaSchrimpf** [SanaMobile/vaccine_registry#50]
We have discussed this before, but I wanted to flag it as a feature that also needs be ready for launch. Once we install a version on the tablets we will not have the manpower to recollect tablets and manually install another version that has this feature.

**Comment by ewinkler** [comment]
Do we have the signed certificate to install on the server available?

**Comment by francineloza** [comment]
Yes we do, I can scp it into the instance once you confirm:

1. Can you confirm that the relevant instance is the one with the following DNS: 
ec2-52-66-146-186.ap-south-1.compute.amazonaws.com

2. In what directory?

**Comment by ewinkler** [comment]
1. That is the correct server.
2. The signed cert should get installed into /etc/ssl/cert/. We will also need the key used to sign the request installed in /etc/ssl/private/.
