### ISSUE TITLE
Client resend trigger

### ISSUE THREAD

**Issue by ewinkler** [SanaMobile/vaccine_registry#53]
Periodic trigger not activating. Retry on connectivity changes is working but the periodic trigger is required for cases where connection may be interrupted for reasons other than client losing all network connectivity.

**Comment by kepaik** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Offline Synchronization](https://trello.com/c/hEf6DLxU/4-offline-synchronization)
