### ISSUE TITLE
Status press Crash

### ISSUE THREAD

**Issue by kepaik** [SanaMobile/vaccine_registry#56]
What does pressing the color square do?
No UI indication.

Also crashes after pressing.

**Comment by ewinkler** [comment]
Changes color based on connectivity.
red=no connectivity
yellow=synch active and items remaining
green=everything up to date
Going to refine visualization. Will add as enhancement.

Testing version: pressing is supposed to force synch and update check.

**Comment by ewinkler** [comment]
Crash is fixed. Same issue that was causing #54.  Visualization could still be better.

**Comment by kepaik** [comment]
Persists.  Crashes after pressing 10+ times...
