### ISSUE TITLE
Test App update sync

### ISSUE THREAD

**Issue by kepaik** [SanaMobile/vaccine_registry#57]

**Comment by ewinkler** [comment]
Staging and production servers are online. Application ids in app should allow for installing both.

**Comment by kepaik** [comment]
#50 
Also, shouldn't there be a "Check for update" button? Or at least text that confirms, "You have the latest version"

**Comment by kepaik** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Over air App update](https://trello.com/c/sCfwPO2I/12-over-air-app-update)

**Comment by kepaik** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [App Synchronization](https://trello.com/c/QEu4XYgi/20-app-synchronization)
