### ISSUE TITLE
Encounters are not being uploaded after reconnecting network

### ISSUE THREAD

**Issue by kepaik** [SanaMobile/vaccine_registry#61]
Tested capturing records without network.
After reactivating network, encounters were not uploaded to server.
Are appearing locally.

Reconnecting and creating a new record only uploads the new record, not the previously created ones.

**Comment by kepaik** [comment]
May be related to #53 ?

**Comment by ewinkler** [comment]
Left out a parameter that was needed for the POST in the Encounter handling from the UI, Should be fixed now.

**Comment by kepaik** [comment]
Error persists

**Comment by kepaik** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Offline Synchronization](https://trello.com/c/hEf6DLxU/4-offline-synchronization)
