### ISSUE TITLE
Last synch time display

### ISSUE THREAD

**Issue by ewinkler** [SanaMobile/vaccine_registry#62]
The display on the main nav screen is not being updated. Should change after all messages in the queue have been sent successfully and the local data store's synch state is considered up to date.

**Comment by kepaik** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Last sync display time](https://trello.com/c/t7wwIMqt/9-last-sync-display-time)

**Comment by AnnaSchrimpf** [comment]
The last sync time often does not display for me.

**Comment by AnnaSchrimpf** [comment]
![img_8388](https://cloud.githubusercontent.com/assets/5496869/19421059/fe5564a6-93c5-11e6-87f7-be4bab9e0145.JPG)
