### ISSUE TITLE
Offline sync New Children not functioning

### ISSUE THREAD

**Issue by kepaik** [SanaMobile/vaccine_registry#73]
#69 not fixed

[offline]
Create new child (SJA000041), record visit
[Reconnect]
No record on server, no vaccination history

Create new encounter
Sync -> New encounter recorded, patient record uploaded.

So, it works partially, only after a new encounter is synced, but does not record the original patient history and first encounter.

**Comment by kepaik** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Offline New Child Sync](https://trello.com/c/KNf1oDOw/21-offline-new-child-sync)

**Comment by ewinkler** [comment]
Check how the encounter send failures are flagged.
