### ISSUE TITLE
[2.1.1-beta-27-staging-en] No encounters from particular tablet display on server 

### ISSUE THREAD

**Issue by AnnaSchrimpf** [SanaMobile/vaccine_registry#78]
Tried online, airplane mode trigger, connecting to different wifis, different logins. This was the case during the performance test and still persists. Status displays as synchronized/ green box.

**Comment by kepaik** [comment]
I believe this is a known synching issue, where the tablet was used before the data was completely synchronized the first time. This is something that we are currently working on to resolve.

**Comment by AnnaSchrimpf** [comment]
This used to occur on my tablet, but seems fixed.
