### ISSUE TITLE
[2.1-27] Crash after "Edit" button is pressed

### ISSUE THREAD

**Issue by kepaik** [SanaMobile/vaccine_registry#8]
App sometimes crashes after “edit" button is pressed:
Again, this triggers the "Unfortunately, Sana has stopped responding” warning in some cases.

**Comment by kepaik** [comment]
Occurred on an earlier version once. Have not been able to replicate yet. Will monitor.

**Comment by AnnaSchrimpf** [comment]
Issue no longer occurring.
