### ISSUE TITLE
[2.1.1-beta-27-staging-en] Successful aadhar scan triggers alert reminder to bring aadhar

### ISSUE THREAD

**Issue by AnnaSchrimpf** [SanaMobile/vaccine_registry#80]
From performance test: Used Aadhaar look-up; The Aadhaar scan worked but I got an alert on the 'Review Registration Information' screen that said "(0901)ALERT! Please remind the caregiver the child AADHAAR or VACC-ID for next visit"

**Comment by ewinkler** [comment]
Successful scan progressing to wrong screen.

**Comment by ewinkler** [comment]
Retry doesn't scan.
