### ISSUE TITLE
[2.1.1-41-beta] Slow to sync

### ISSUE THREAD

**Issue by AnnaSchrimpf** [SanaMobile/vaccine_registry#84]
15+ minutes to complete synchronization after adding children offline and reconnecting 
(with MIT wifi connection and few records - presumably this would be worse in field)

**Comment by kepaik** [comment]
Was this the first time logging in or after an offline test?

First sync will be longer than regular syncs, but shouldn't be 15 minutes.

**Comment by AnnaSchrimpf** [comment]
After an offline test. Based on the progress bar, I reach 75% within a minute or so, but then don't progress beyond. This is not consistent, however. 

The initial sync takes about 2 min to complete.

**Comment by kepaik** [comment]
Ah, that may be related to #88 then...

**Comment by AnnaSchrimpf** [comment]
So I abandoned the sync after offline test, and tried an initial sync for a login I hadn't used (ANM001) - which now is handing as well.

**Comment by kepaik** [comment]
Yes, this is related to #88.  It kills the sync queue.  Investigating.  
I can't seem to be able to get around the issue as well.
In order to continue testing, I would recommend actually uninstalling and reinstalling to clear the faulty message queue.

**Comment by AnnaSchrimpf** [comment]
Ok, will do.

**Comment by ewinkler** [comment]
There is a lock on the message queue which is in place to prevent resending the same message(s) repeatedly. I suspect the unlock mechanism on it is not behaving well.

**Comment by AnnaSchrimpf** [comment]
Issue persists after re-install.

**Comment by kepaik** [comment]
Persists without the offline sync logout? 
Or even on a fresh install?

We think we have a lead to the offline resync issue, but if you're coming across the same issue without an offline test case, could you describe further the details on the lead up to the sync?
