### ISSUE TITLE
[2.1.1-41-beta]  Vaccination History improperly synced to across tablets 

### ISSUE THREAD

**Issue by AnnaSchrimpf** [SanaMobile/vaccine_registry#86]
Logged into to tablet, scanned returning child. 
The child was found
the vaccination history of the child was not

**Comment by kepaik** [comment]
When was the child history created?
Was the prior data from the other tablet synchronized with the backend?

**Comment by AnnaSchrimpf** [comment]
Yes, data was synced. It displayed an empty history after looking up on the tablet 2 (which technically should never exist). Have not yet been able to replicate the issue again.

**Comment by AnnaSchrimpf** [comment]
![img_8403](https://cloud.githubusercontent.com/assets/5496869/19665174/b9b701f4-9a11-11e6-8116-8a3e4e90f79c.JPG)

**Comment by kepaik** [comment]
Possibly related to #88 and #84 . Monitor.
