### ISSUE TITLE
[2.1.1-41-beta] No advance after successful aadhaar scan

### ISSUE THREAD

**Issue by AnnaSchrimpf** [SanaMobile/vaccine_registry#87]
After scan of aadhar, does not advance to the next page. 
manual entry was successful 

Steps:
Logged into to tablet, scanned returning child AADHAR 
Returned to the same page as I was intitally on

**Comment by kepaik** [comment]
Does this happen consistently?
I cannot replicate on local device.
And this is after pressing "Accept" after successful scan?

**Comment by AnnaSchrimpf** [comment]
Yes, this is a consistent problem for us. Note however that we don't have the exact same tablets used in the field (because the model is unavailable in the US). We are using Galaxy Tab A (2016) Model number SM-T280, Android 5.1.1, which is the closest we could get.

**Comment by kepaik** [comment]
So to clarify the steps:

1) Start encounter
2) [A1] Scanning child aadhar
3) Scan app opens and read code
4) "Scan result: 979876451397; Press Accept to confirm or Retry to scan again" pops up
5) You press "Accept"
6) Then it takes you to... which screen?  The [A1] Screen or the "welcome back" home screen, or the "login screen"?

Is this will any aadhar?

I am testing with the EAadhaar version without problems on 2 devices, so am trying to narrow down.

**Comment by AnnaSchrimpf** [comment]
re 6) it takes me back to [A1]  Scan Child Aadhaar screen.

For caregiver aadhaar screen it progresses as expected.
I only have one aadhaar available right now, but the issue arises for both tablets I'm using to test.

**Comment by ewinkler** [comment]
Is a patient with that AADHAR already registered? I can't seem to replicate but I have already used the AADHAR for a patient so I am wondering if it is just happening in the case when the patient has not been previously registered.

**Comment by AnnaSchrimpf** [comment]
This one has been registered (3823 5789 9476). I can look up manually.

**Comment by kepaik** [comment]
Could you email me that AADHAR?

**Comment by AnnaSchrimpf** [comment]
I tried the adult aadhaar and I can progress beyond [A1] using that (successful lookup).

**Comment by kepaik** [comment]
Yes, I have replicated your problems with yours. Seems like it must be a validation/check issue. Will investigate further.

**Comment by ewinkler** [comment]
I was finally able to replicate. Working on a fix.

**Comment by AnnaSchrimpf** [comment]
Not sure whether this could have anything to do with it (as I'm not sure whether the address is parsed at all), but could the problem arise bc of the dashes in the child's aadhaar address?

**Comment by kepaik** [comment]
It turned out to be that there were duplicate records, which caused an exception.  Eric has fixed it in the development version, which I am currently testing.
