### ISSUE TITLE
[2.1.1-41-beta] Connection status displays as complete/green but not all records uploaded

### ISSUE THREAD

**Issue by AnnaSchrimpf** [SanaMobile/vaccine_registry#88]

**Comment by AnnaSchrimpf** [comment]
e.g. entered record offline, connect to wifi, sync status displays as green/complete upon login, but record does not display on server

**Comment by kepaik** [comment]
Do you log out while still offline and then reconnect after login?  Or from your wording, I guess you reconnect after you logout, but before you login?

**Comment by kepaik** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [issue88: Sync issues between connections](https://trello.com/c/l9tdoqUk/85-issue88-sync-issues-between-connections)

**Comment by kepaik** [comment]
Replicated... Looking into it.

**Comment by AnnaSchrimpf** [comment]
OK!

**Comment by AnnaSchrimpf** [comment]
I replicated this issue also in following scenario:
[all online]
1) create new child encounter [sja000D8] as anm07
2) logout
3) login as anm6 
4) lookup sja000D8 via barcode and complete encounter
5) sync displays as complete on homescreen 
6) record sja000DB appears in daily report but not on server
7) log out of anm6 and log in again -> sync -> record on server
