### ISSUE TITLE
[2.1.1-41-beta] Timeline for Hindi version

### ISSUE THREAD

**Issue by AnnaSchrimpf** [SanaMobile/vaccine_registry#89]
This is not an "issue" per se, but I was hoping to get a sense of when you will be able to share a Hindi version of this release? This is less for the launch than for the screenshots we need to finalize all our training materials across training presentations for master trainers, ANMs, implementation teams, various handbooks, SOPs, etc. 

Even if there are outstanding issues it would be very helpful for the team to have the Hindi screenshots as soon as possible, because our training materials also need to undergo review by various government officials before we can go ahead and I want to avoid an approval bottleneck if at all possible. So short of any UI changes (I'm not aware of any at this point?) it would be great if you could make the production of the Hindi version a priority.

**Comment by kepaik** [comment]
I'm working on the translation piece and am compiling a new spreadsheet to better grab some outstanding segments.

We will look into getting a hindi version released with an interval update that will address a few of the issues you just uncovered, maybe later today.
