### ISSUE TITLE
[2.1.1-41-beta] After re-installation only top 2 boxes of homescreen display

### ISSUE THREAD

**Issue by AnnaSchrimpf** [SanaMobile/vaccine_registry#90]
Deleted and re-installed the app, waited for sync to complete, sync completed but homescreen does not display login/ report boxes. (see screenshot). Not a consistent issue.

**Comment by AnnaSchrimpf** [comment]
![img_8405](https://cloud.githubusercontent.com/assets/5496869/19662719/d2ec9a9a-9a06-11e6-9826-791e811dde65.JPG)

**Comment by ewinkler** [comment]
Curious. It is supposed to block the lower boxes until the initial synch completes but I will look into why it isn't displaying them after the reinstall.

**Comment by kepaik** [comment]
Was this the first time you logged in?
What happens if you log out and log back in? Does it persist?

**Comment by AnnaSchrimpf** [comment]
Yes, first time. Issue resolved by logging in and out.
