### ISSUE TITLE
[2.1.1-47-beta] Check now button unresponsive

### ISSUE THREAD

**Issue by AnnaSchrimpf** [SanaMobile/vaccine_registry#93]
On of the two tablets I am testing with, pressing "Check now" button does not trigger "Checking..." message (or any other message) and does not trigger download. Status showing as connected. (IP 18.111.124.177) Issue persists after logging in and out but is resolved by quitting and restarting the app. (The update via "check now" path worked fine for other tablet without logging in and out etc). To be clear, issue occurs during attempt update from 1.41 to 1.47 beta.

**Comment by kepaik** [comment]
Was this immediately after install or was there some other process before then? Did you perhaps attempt an offline data entry and reconnect?

**Comment by AnnaSchrimpf** [comment]
This was before the download/upgrade to .47 version; after logging in (online) with .41 version.
