### ISSUE TITLE
[2.1.1-47-beta] Record edits don't sync across tablets

### ISSUE THREAD

**Issue by AnnaSchrimpf** [SanaMobile/vaccine_registry#94]
Edited surname name of child 3822 5798 9476 from "s" to "schrimpf." Record updated correctly on server. Switched tablet. Logged in as different ANM. Status displays as green. Look-up through either aadhar or barcode still displays "s" as surname. Changed name again to "banana." Switched tablet. Log in and sync as different ANM. Surname now displays as "schrimpf" when looked up (i.e. seems to lag behind edits).

**Comment by kepaik** [comment]
Yes, this is related to  #92.

**Comment by AnnaSchrimpf** [comment]
Ok, should I disregard any sync issues for now?
